services:
  beets-flask:
    container_name: beets-flask
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - '5001:5001'
    volumes:
      - ./config/:/config
      - /Volumes/Price_music/inbox:/music/inbox
      - /Volumes/Price_music:/music/imported
      - ./logs/:/logs
    environment:
      TZ: America/Toronto
      USER_ID: 502
      GROUP_ID: 140
